# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import stream_twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_twitter', '0001_squashed_0002_auto_20170929_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(
                stream_twitter.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(
                stream_twitter.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
